server:
  port: 8090

spring:
  application:
    name: edu-config-boot

  cloud:
    config:
      server:
        git:
          uri: https://gitee.com/lankkk/lank-edu-repo.git
          default-label: master
logging:
  level:
    org.springframework.cloud: debug